### ISSUE TITLE
Assertion Error: "" when attempting to scale_sector_sizes without make_maximal_diffs set to true

### ISSUE THREAD

**Issue by nathansmith11170** [bvbohnen/X4_Customizer#2]
Problem can be recreated by making a script that resizes sectors and calling Write_To_Extension with preference set to loose files.
example script:
```
from Plugins import *

if 1:
    Scale_Sector_Size(
        scaling_factor                     = 0.3,
        scaling_factor_2                   = 0.25,
        transition_size_start              = 200000,
        transition_size_end                = 400000,
        precision_steps                    = 20,
        remove_ring_highways               = True,
        remove_nonring_highways            = True,
        extra_scaling_for_removed_highways = 0.7,
        move_free_ships = True,
        debug = True
        )

Write_To_Extension()
```

traceback:
```
Traceback (most recent call last):
  File "Main.py", line 253, in Run
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\X4 Customizer\X4_Customizer_v1.24\Scripts\Vash transforms.py", line 44, in <module>
    Write_To_Extension()
  File "Common\Plugin_Manager.py", line 163, in wrapper
  File "Common\Plugin_Manager.py", line 138, in wrapper
  File "D:\X4 Customizer\X4_Customizer_v1.24\Plugins\Utilities\Write_Mod_Files.py", line 67, in Write_To_Extension
    File_System.Write_Files()
  File "File_Manager\File_System.py", line 87, in func_wrapper
  File "File_Manager\File_System.py", line 643, in Write_Files
  File "File_Manager\File_Types.py", line 769, in Write_File
  File "File_Manager\File_Types.py", line 739, in Get_Binary
  File "File_Manager\File_Types.py", line 707, in Get_Diff
  File "File_Manager\XML_Diff.py", line 629, in Make_Patch
  File "File_Manager\XML_Diff.py", line 772, in _Get_Patch_Ops_Recursive
AssertionError
```

**Comment by bvbohnen** [comment]
Testing with just official dlc didn't reproduce the error.

Are any other extensions in use?  Does this happen with other extensions disabled?

**Comment by nathansmith11170** [comment]
At the time that I tested this I had just reinstalled the game on a new PC. Now I have a bunch of other extensions, so it would be difficult to try and produce the error again.
